# NAME: ANSH PUJARA
# AI - ML BATCH 1
# ASSIGNMENT FOR DAY 14 - 15

In [2]:
import numpy as np
import pandas as pd

## 1. Create a 3x3x3 array with random values

In [4]:
x = np.random.random((3,3,3))
x

array([[[0.09803601, 0.86422871, 0.05035607],
        [0.76835146, 0.42655264, 0.25279036],
        [0.51400326, 0.53878327, 0.37021826]],

       [[0.55620106, 0.44445865, 0.07428903],
        [0.93398294, 0.88195819, 0.78026361],
        [0.56387738, 0.2627856 , 0.91344782]],

       [[0.69793753, 0.63262029, 0.58162464],
        [0.95494507, 0.16505112, 0.87356576],
        [0.34983084, 0.30059163, 0.772874  ]]])

## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
a = np.diag(1+np.arange(4), -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
a = np.zeros((8,8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 4. Normalize a 5x5 random matrix

In [12]:
a = np.random.random((5,5))
b = (a - a.min())/(a.max() - a.min())
print(b)

[[0.3533971  0.937082   0.44096446 0.09245236 0.75116614]
 [0.05945959 0.54324193 0.92960326 0.96877017 0.70429194]
 [1.         0.24047034 0.21921056 0.53381219 0.68261078]
 [0.44816722 0.87119801 0.60677512 0.76780464 0.        ]
 [0.40843675 0.93951829 0.84780971 0.18976113 0.89020845]]


## 5. How to find common values between two arrays?

In [17]:
a = [1, 2, 3, 5, 6, 8, 9]
b = [1, 2, 4, 6, 9, 11]
np.intersect1d(a, b)

array([1, 2, 6, 9])

## 6.How to get the dates of yesterday, today and tomorrow?

In [35]:
today = datetime.date.today()
print(today)

2020-07-29


In [32]:
yesterday = today - datetime.timedelta(days=1)
print(yesterday)

2020-07-28


## 7. Consider two random array A and B, check if they are equal

In [36]:
a = [1, 2, 3, 5, 6, 8, 9]
b = [1, 2, 4, 6, 9, 11, 12]
a == b

False

## 8.Create random vector of size 10 and replace the maximum value by 0

In [40]:
vec = np.random.random(10)
vec[vec.argmax()] = 0
vec

array([0.        , 0.1421015 , 0.5505255 , 0.38060436, 0.24526101,
       0.78443222, 0.62309604, 0.02821508, 0.01727856, 0.64566573])

## 9. How to print all the values of an array?

In [41]:
print(vec)

[0.         0.1421015  0.5505255  0.38060436 0.24526101 0.78443222
 0.62309604 0.02821508 0.01727856 0.64566573]


## 10.Subtract the mean of each row of a matrix

In [44]:
x = np.random.random((3,3))
y = x - x.mean(axis=1)
print(y)

[[ 0.08203704  0.30748382  0.46626459]
 [-0.01555797 -0.25462703  0.15775074]
 [-0.44380723 -0.02944756 -0.2700964 ]]


## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [45]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 2. 1. 5. 4. 2. 2. 2. 4.]


## 12.How to get the diagonal of a dot product?

In [47]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
np.diag(np.dot(a, b))

array([133,  38, 146])

## 13.How to find the most frequent value in an array?

In [53]:
k = np.random.randint(0,10,50)
print(np.bincount(k).argmax())

7


## 14.How to get the n largest values of an array

In [54]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


## 15.How to create a record array from a regular array?

In [55]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [56]:
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
