# NAME: ANSH PUJARA
# AI / ML BATCH - 1
# ASSIGNMENT DAY - 25

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn import preprocessing

## Importing data

In [2]:
data = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data['Sex'] = data['Sex'].map({'male':1, 'female':0})
test['Sex'] = test['Sex'].map({'male':1, 'female':0})

In [10]:
data['Embarked'] = data['Embarked'].map({'S':1, 'C':2, 'Q':3})
test['Embarked'] = test['Embarked'].map({'S':1, 'C':2, 'Q':3})

In [11]:
from sklearn.naive_bayes import *

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix

## Training

### 1. DV - Survived &nbsp;    IDV - remaining columns

In [32]:
y = data['Survived']
x = data.drop(['Survived', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

In [34]:
clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)

In [35]:
surv_acc = accuracy_score(y_test, y_pred, normalize = True)
surv_acc

0.8089887640449438

In [17]:
confusion_matrix(y_test, y_pred)

array([[90, 17],
       [17, 54]], dtype=int64)

### 2. DV - Pclass &nbsp;    IDV - remaining columns

In [36]:
y = data['Pclass']
x = data.drop(['Pclass', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

In [38]:
clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)

In [39]:
pvclass_acc = accuracy_score(y_test, y_pred, normalize = True)

In [40]:
pvclass_acc

0.601123595505618

In [22]:
confusion_matrix(y_test, y_pred)

array([[28,  0, 24],
       [18,  0, 17],
       [11,  1, 79]], dtype=int64)

### 3. DV - Sex &nbsp;    IDV - remaining columns

In [41]:
y = data['Sex']
x = data.drop(['Sex', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)

sx_acc = accuracy_score(y_test, y_pred, normalize = True)

confusion_matrix(y_test, y_pred)

array([[54, 17],
       [16, 91]], dtype=int64)

In [42]:
print(accuracy_score(y_test, y_pred, normalize = True))

0.8146067415730337


### 4. DV - SibSp &nbsp;    IDV - remaining columns

In [43]:
y = data['SibSp']
x = data.drop(['SibSp', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)
sibsp_acc = accuracy_score(y_test, y_pred, normalize = True)
print(sibsp_acc)
confusion_matrix(y_test, y_pred)

0.7078651685393258


array([[114,  12,   0,   0,   0,   0],
       [ 27,  12,   0,   0,   0,   0],
       [  2,   1,   0,   0,   0,   0],
       [  3,   5,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0,   0]], dtype=int64)

### 5. DV - Embarked &nbsp;    IDV - remaining columns

In [44]:
y = data['Embarked']
x = data.drop(['Embarked', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)
emb = accuracy_score(y_test, y_pred, normalize = True)
print(emb)
confusion_matrix(y_test, y_pred)

0.702247191011236


array([[125,   0,   0],
       [ 38,   0,   0],
       [ 15,   0,   0]], dtype=int64)

### 6. DV - ParCh &nbsp;    IDV - remaining columns

In [46]:
y = data['Parch']
x = data.drop(['Parch', 'PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 320, test_size = 0.2)

clf = BernoulliNB()
y_pred = clf.fit(x_train, y_train).predict(x_test)
par = accuracy_score(y_test, y_pred, normalize = True)
print(par)
confusion_matrix(y_test, y_pred)

0.7191011235955056


array([[125,  10,   0,   0,   0],
       [ 18,   3,   0,   0,   0],
       [ 14,   6,   0,   0,   0],
       [  1,   0,   0,   0,   0],
       [  1,   0,   0,   0,   0]], dtype=int64)

## Accuracy Score table

In [47]:
table = pd.DataFrame({"DV":['Survived', 'Pclass', 'Sex', 'Sibsp', 'Embarked', 'Parch'], "Acc_Score":[surv_acc, pclass_acc, sx_acc, sibsp_acc, emb, par]})
table

NameError: name 'pclass_acc' is not defined